steps:
 
  # Build and push fastapi docker images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/forward-server-390416/fastapi:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/forward-server-390416/fastapi:$COMMIT_SHA'
# logsBucket: 'my-logs-bucket'
